### ISSUE TITLE
Swiping With Iron-Image

### ISSUE THREAD

**Issue by hakanyildiz** [safetychanger/iron-swiper#11]
I used iron-swiper dinamically. I got my data from db, and adding to swiper with dom-repeat. There is no problem when i used to "img" tag. But when I try to use Iron-image instead of img , images  is not showing.  How can I fix it?
Thanks.

**Comment by rubenstolk** [comment]
@hakanyildiz I need to look into this, currently this is a wrapper around Swiper.js which does the actual rendering, hence it might fail at Polymer elements inside.

We might have to add something here https://github.com/safetychanger/iron-swiper/blob/master/iron-swiper.html#L362 for the Swiper stuff to be injected into the shadow dom or whatever.

 I'm actually looking into merging this project with @MeTaNov's `iron-swipeable-pages` so that we don't need external libraries anymore.

**Comment by hakanyildiz** [comment]
Thanks for response TCOY.

**Comment by rubenstolk** [comment]
I don't think this will work as this uses a non-Polymer wrapper. Closing it for now.
